### ISSUE TITLE
Sections should use Language name rather than Country name

### ISSUE THREAD

**Issue by MrSkwiggs** [matteofabbri/EuropeanGreatAtlasOfProfanities#4]
For instance, Belgium is currently only displaying Flemish (Dutch) slurs & cursing, but Belgians also speak French & German. 

Therefore, the list would make more sense as a list of curse words in different languages rather than in different countries.

**Comment by matteofabbri** [comment]
At the beginning it was using languages instead of countries, which was also a mistake because same language doesn't always mean same meaning, expecially in this field,
The good way to go, IMHO, should be nation than language, as the same of keyboard.
Sadly, being a contribution oriented project is biased by contribution cultures, I hope we cam growth enoguh to have a separated place for each country with all its language inside, 
Obs, if you have any not Flemish  slur to add, I will be very happy to add them <3

**Comment by MrSkwiggs** [comment]
@matteofabbri well I've added the french slurs to the France part, but they'd also work for the Belgian-french part too
